import dynamic from 'next/dynamic';

import '@/styles/globals.css';

const Header = dynamic(() => import('@/components/Header'), {
  ssr: false,
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-[100vh] bg-gray-900">
          <Header />
          <div className="text-white">{children}</div>
        </div>
      </body>
    </html>
  );
}
