import dynamic from 'next/dynamic';
import { HeaderLoading } from '@/components/Header/Header';

import '@/styles/globals.css';

const Header = dynamic(() => import('@/components/Header'), {
  ssr: false,
  loading: () => <HeaderLoading />,
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-[calc(100vh-56px)] bg-gray-900">
        <Header />
        <main className="text-white">{children}</main>
      </body>
    </html>
  );
}
