import Header from '@/components/Header';
import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-[100vh] bg-gray-900">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
